"""crear tabla colecciones

Revision ID: 04ef7efb7aaf
Revises: 8dc8d70953ad
Create Date: 2026-08-15 16:23:31.497587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04ef7efb7aaf'
down_revision: Union[str, Sequence[str], None] = '8dc8d70953ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colecciones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_tienda', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_tienda'], ['shop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_colecciones_id'), 'colecciones', ['id'], unique=False)
    op.create_index(op.f('ix_colecciones_id_tienda'), 'colecciones', ['id_tienda'], unique=False)
    op.create_table('coleccion_producto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('coleccion_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['coleccion_id'], ['colecciones.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coleccion_producto_coleccion_id'), 'coleccion_producto', ['coleccion_id'], unique=False)
    op.create_index(op.f('ix_coleccion_producto_producto_id'), 'coleccion_producto', ['producto_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coleccion_producto_producto_id'), table_name='coleccion_producto')
    op.drop_index(op.f('ix_coleccion_producto_coleccion_id'), table_name='coleccion_producto')
    op.drop_table('coleccion_producto')
    op.drop_index(op.f('ix_colecciones_id_tienda'), table_name='colecciones')
    op.drop_index(op.f('ix_colecciones_id'), table_name='colecciones')
    op.drop_table('colecciones')
    # ### end Alembic commands ###
