"""tablas nuevas

Revision ID: 0f162b8a4bda
Revises: 7c01341e0175
Create Date: 2026-08-27 14:38:20.591793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f162b8a4bda'
down_revision: Union[str, Sequence[str], None] = '7c01341e0175'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('al_por_mayor',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_tienda', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.Column('cantidad_minima', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_tienda'], ['shop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_al_por_mayor_id'), 'al_por_mayor', ['id'], unique=False)
    op.create_index(op.f('ix_al_por_mayor_id_tienda'), 'al_por_mayor', ['id_tienda'], unique=True)
    op.add_column('productos', sa.Column('precio_alpormayor', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productos', 'precio_alpormayor')
    op.drop_index(op.f('ix_al_por_mayor_id_tienda'), table_name='al_por_mayor')
    op.drop_index(op.f('ix_al_por_mayor_id'), table_name='al_por_mayor')
    op.drop_table('al_por_mayor')
    # ### end Alembic commands ###
