"""crear tabla promociones

Revision ID: 233999b8e11d
Revises: 2bbb3cb56f76
Create Date: 2026-08-16 23:08:11.345329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '233999b8e11d'
down_revision: Union[str, Sequence[str], None] = '2bbb3cb56f76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promociones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_tienda', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('descuento', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_tienda'], ['shop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promociones_id'), 'promociones', ['id'], unique=False)
    op.create_index(op.f('ix_promociones_id_tienda'), 'promociones', ['id_tienda'], unique=False)
    op.create_table('promocion_producto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('promocion_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['promocion_id'], ['promociones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('promocion_id', 'producto_id')
    )
    op.create_index(op.f('ix_promocion_producto_producto_id'), 'promocion_producto', ['producto_id'], unique=False)
    op.create_index(op.f('ix_promocion_producto_promocion_id'), 'promocion_producto', ['promocion_id'], unique=False)
    op.create_table('promociones_unitarias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_tienda', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('descuento', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['id_tienda'], ['shop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promociones_unitarias_id'), 'promociones_unitarias', ['id'], unique=False)
    op.create_index(op.f('ix_promociones_unitarias_id_producto'), 'promociones_unitarias', ['id_producto'], unique=False)
    op.create_index(op.f('ix_promociones_unitarias_id_tienda'), 'promociones_unitarias', ['id_tienda'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_promociones_unitarias_id_tienda'), table_name='promociones_unitarias')
    op.drop_index(op.f('ix_promociones_unitarias_id_producto'), table_name='promociones_unitarias')
    op.drop_index(op.f('ix_promociones_unitarias_id'), table_name='promociones_unitarias')
    op.drop_table('promociones_unitarias')
    op.drop_index(op.f('ix_promocion_producto_promocion_id'), table_name='promocion_producto')
    op.drop_index(op.f('ix_promocion_producto_producto_id'), table_name='promocion_producto')
    op.drop_table('promocion_producto')
    op.drop_index(op.f('ix_promociones_id_tienda'), table_name='promociones')
    op.drop_index(op.f('ix_promociones_id'), table_name='promociones')
    op.drop_table('promociones')
    # ### end Alembic commands ###
