"""tabla de colecciones para los allimentos

Revision ID: 269f399c335c
Revises: 71240a6f6180
Create Date: 2026-08-26 15:49:55.214371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '269f399c335c'
down_revision: Union[str, Sequence[str], None] = '71240a6f6180'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colecciones_alimentos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_tienda', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_tienda'], ['shop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_colecciones_alimentos_id'), 'colecciones_alimentos', ['id'], unique=False)
    op.create_index(op.f('ix_colecciones_alimentos_id_tienda'), 'colecciones_alimentos', ['id_tienda'], unique=False)
    op.create_table('coleccion_alimento',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('coleccion_id', sa.Integer(), nullable=False),
    sa.Column('alimento_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['alimento_id'], ['alimentos.id'], ),
    sa.ForeignKeyConstraint(['coleccion_id'], ['colecciones_alimentos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coleccion_id', 'alimento_id', name='uq_coleccion_alimento')
    )
    op.create_index(op.f('ix_coleccion_alimento_alimento_id'), 'coleccion_alimento', ['alimento_id'], unique=False)
    op.create_index(op.f('ix_coleccion_alimento_coleccion_id'), 'coleccion_alimento', ['coleccion_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coleccion_alimento_coleccion_id'), table_name='coleccion_alimento')
    op.drop_index(op.f('ix_coleccion_alimento_alimento_id'), table_name='coleccion_alimento')
    op.drop_table('coleccion_alimento')
    op.drop_index(op.f('ix_colecciones_alimentos_id_tienda'), table_name='colecciones_alimentos')
    op.drop_index(op.f('ix_colecciones_alimentos_id'), table_name='colecciones_alimentos')
    op.drop_table('colecciones_alimentos')
    # ### end Alembic commands ###
