"""tabla de pedidos para  los alimentos

Revision ID: 2a7dd4fd9ce5
Revises: 52bec42b138f
Create Date: 2026-08-26 16:51:38.741804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a7dd4fd9ce5'
down_revision: Union[str, Sequence[str], None] = '52bec42b138f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pedidos_alimentos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_tienda', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('direccion', sa.String(length=250), nullable=True),
    sa.Column('domicilio', sa.Boolean(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_tienda'], ['shop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pedidos_alimentos_id'), 'pedidos_alimentos', ['id'], unique=False)
    op.create_index(op.f('ix_pedidos_alimentos_id_tienda'), 'pedidos_alimentos', ['id_tienda'], unique=False)
    op.create_table('pedido_alimento_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('alimento_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['alimento_id'], ['alimentos.id'], ),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos_alimentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pedido_alimento_items_alimento_id'), 'pedido_alimento_items', ['alimento_id'], unique=False)
    op.create_index(op.f('ix_pedido_alimento_items_pedido_id'), 'pedido_alimento_items', ['pedido_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pedido_alimento_items_pedido_id'), table_name='pedido_alimento_items')
    op.drop_index(op.f('ix_pedido_alimento_items_alimento_id'), table_name='pedido_alimento_items')
    op.drop_table('pedido_alimento_items')
    op.drop_index(op.f('ix_pedidos_alimentos_id_tienda'), table_name='pedidos_alimentos')
    op.drop_index(op.f('ix_pedidos_alimentos_id'), table_name='pedidos_alimentos')
    op.drop_table('pedidos_alimentos')
    # ### end Alembic commands ###
