"""atributo plantillas en shop

Revision ID: 2a9d8cc57a77
Revises: bac41985133a
Create Date: 2026-08-22 12:47:15.003791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a9d8cc57a77'
down_revision: Union[str, Sequence[str], None] = 'bac41985133a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop', sa.Column('pantilla', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop', 'pantilla')
    # ### end Alembic commands ###
