"""agregar total en pedidos

Revision ID: 2b9a06a7d8ad
Revises: 0c18da2e3da6
Create Date: 2026-08-17 17:34:19.759543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b9a06a7d8ad'
down_revision: Union[str, Sequence[str], None] = '0c18da2e3da6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedidos', sa.Column('totalcompra', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pedidos', 'totalcompra')
    # ### end Alembic commands ###
