"""crear tabla estilos

Revision ID: 2bbb3cb56f76
Revises: 04ef7efb7aaf
Create Date: 2026-08-16 11:47:27.550208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bbb3cb56f76'
down_revision: Union[str, Sequence[str], None] = '04ef7efb7aaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estilos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_tienda', sa.Integer(), nullable=False),
    sa.Column('color_principal', sa.String(length=7), nullable=False),
    sa.Column('color_secundario', sa.String(length=7), nullable=False),
    sa.Column('title_color', sa.String(length=7), nullable=False),
    sa.Column('text_color', sa.String(length=7), nullable=False),
    sa.Column('imagen_fondo', sa.String(length=300), nullable=True),
    sa.Column('color_carrito', sa.String(length=7), nullable=False),
    sa.Column('color_botones', sa.String(length=7), nullable=False),
    sa.ForeignKeyConstraint(['id_tienda'], ['shop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estilos_id'), 'estilos', ['id'], unique=False)
    op.create_index(op.f('ix_estilos_id_tienda'), 'estilos', ['id_tienda'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_estilos_id_tienda'), table_name='estilos')
    op.drop_index(op.f('ix_estilos_id'), table_name='estilos')
    op.drop_table('estilos')
    # ### end Alembic commands ###
