"""atributo obligatorio a opcional en alimentos

Revision ID: 4796420907e6
Revises: 53d09fc67750
Create Date: 2026-08-26 15:21:41.419491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4796420907e6'
down_revision: Union[str, Sequence[str], None] = '53d09fc67750'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ingredientes', 'cantidad',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ingredientes', 'cantidad',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
