"""crear tabla

Revision ID: 4b1a0d6a4af5
Revises: 362080a5abc3
Create Date: 2026-08-13 15:24:46.876218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b1a0d6a4af5'
down_revision: Union[str, Sequence[str], None] = '362080a5abc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('cedula', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('nombres', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=False),
    sa.Column('ciudad', sa.String(length=100), nullable=False),
    sa.Column('direccion', sa.String(length=150), nullable=False),
    sa.Column('fecha_nacimieno', sa.Date(), nullable=False),
    sa.Column('correo', sa.String(length=150), nullable=False),
    sa.Column('telefono', sa.String(length=10), nullable=False),
    sa.Column('contraseña', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('cedula')
    )
    op.create_index(op.f('ix_users_cedula'), 'users', ['cedula'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_cedula'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
