"""tabla alimentos

Revision ID: 53d09fc67750
Revises: bf63a0d52e37
Create Date: 2026-08-26 14:33:18.667060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '53d09fc67750'
down_revision: Union[str, Sequence[str], None] = 'bf63a0d52e37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alimentos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_tienda', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('precio', sa.Integer(), nullable=False),
    sa.Column('imagen', sa.String(length=250), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.Column('disponible', sa.Boolean(), nullable=False),
    sa.Column('tiempo_preparacion', sa.Integer(), nullable=True),
    sa.Column('creado_fecha', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_tienda'], ['shop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alimentos_id'), 'alimentos', ['id'], unique=False)
    op.create_index(op.f('ix_alimentos_id_tienda'), 'alimentos', ['id_tienda'], unique=False)
    op.create_table('ingredientes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_tienda', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('unidad', sa.String(length=30), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_tienda'], ['shop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredientes_id'), 'ingredientes', ['id'], unique=False)
    op.create_index(op.f('ix_ingredientes_id_tienda'), 'ingredientes', ['id_tienda'], unique=False)
    op.create_table('alimentos_ingredientes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alimento_id', sa.Integer(), nullable=False),
    sa.Column('ingrediente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['alimento_id'], ['alimentos.id'], ),
    sa.ForeignKeyConstraint(['ingrediente_id'], ['ingredientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alimentos_ingredientes_alimento_id'), 'alimentos_ingredientes', ['alimento_id'], unique=False)
    op.create_index(op.f('ix_alimentos_ingredientes_id'), 'alimentos_ingredientes', ['id'], unique=False)
    op.create_index(op.f('ix_alimentos_ingredientes_ingrediente_id'), 'alimentos_ingredientes', ['ingrediente_id'], unique=False)
    op.drop_constraint(op.f('fk_pedido_producto_variante'), 'pedido_producto', type_='foreignkey')
    op.create_foreign_key(None, 'pedido_producto', 'productos_variantes', ['id_variante'], ['id'])
    op.create_index(op.f('ix_productos_colores_id'), 'productos_colores', ['id'], unique=False)
    op.alter_column('productos_variantes', 'producto_idcolor',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_productos_variantes_producto_idcolor'), 'productos_variantes', ['producto_idcolor'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_productos_variantes_producto_idcolor'), table_name='productos_variantes')
    op.alter_column('productos_variantes', 'producto_idcolor',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_productos_colores_id'), table_name='productos_colores')
    op.drop_constraint(None, 'pedido_producto', type_='foreignkey')
    op.create_foreign_key(op.f('fk_pedido_producto_variante'), 'pedido_producto', 'productos_variantes', ['id_variante'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_alimentos_ingredientes_ingrediente_id'), table_name='alimentos_ingredientes')
    op.drop_index(op.f('ix_alimentos_ingredientes_id'), table_name='alimentos_ingredientes')
    op.drop_index(op.f('ix_alimentos_ingredientes_alimento_id'), table_name='alimentos_ingredientes')
    op.drop_table('alimentos_ingredientes')
    op.drop_index(op.f('ix_ingredientes_id_tienda'), table_name='ingredientes')
    op.drop_index(op.f('ix_ingredientes_id'), table_name='ingredientes')
    op.drop_table('ingredientes')
    op.drop_index(op.f('ix_alimentos_id_tienda'), table_name='alimentos')
    op.drop_index(op.f('ix_alimentos_id'), table_name='alimentos')
    op.drop_table('alimentos')
    # ### end Alembic commands ###
