"""crear tabla pedidos

Revision ID: 543f85ab3955
Revises: ac764abd4fd0
Create Date: 2026-08-17 16:14:39.723166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '543f85ab3955'
down_revision: Union[str, Sequence[str], None] = 'ac764abd4fd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pedidos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_tienda', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_tienda'], ['shop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pedidos_id'), 'pedidos', ['id'], unique=False)
    op.create_index(op.f('ix_pedidos_id_tienda'), 'pedidos', ['id_tienda'], unique=False)
    op.create_table('pedido_producto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('id_tienda', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_tienda'], ['shop.id'], ),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pedido_producto_id_tienda'), 'pedido_producto', ['id_tienda'], unique=False)
    op.create_index(op.f('ix_pedido_producto_pedido_id'), 'pedido_producto', ['pedido_id'], unique=False)
    op.create_index(op.f('ix_pedido_producto_producto_id'), 'pedido_producto', ['producto_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pedido_producto_producto_id'), table_name='pedido_producto')
    op.drop_index(op.f('ix_pedido_producto_pedido_id'), table_name='pedido_producto')
    op.drop_index(op.f('ix_pedido_producto_id_tienda'), table_name='pedido_producto')
    op.drop_table('pedido_producto')
    op.drop_index(op.f('ix_pedidos_id_tienda'), table_name='pedidos')
    op.drop_index(op.f('ix_pedidos_id'), table_name='pedidos')
    op.drop_table('pedidos')
    # ### end Alembic commands ###
