"""atributo en informacion

Revision ID: 60618233de22
Revises: bff0be47db82
Create Date: 2026-09-04 19:55:55.475840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60618233de22'
down_revision: Union[str, Sequence[str], None] = 'bff0be47db82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tuinformacion', sa.Column('foto', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tuinformacion', 'foto')
    # ### end Alembic commands ###
