"""atributos nuevos

Revision ID: 70040e1f1de3
Revises: 8abf1026d09a
Create Date: 2026-08-30 23:47:04.189110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '70040e1f1de3'
down_revision: Union[str, Sequence[str], None] = '8abf1026d09a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedidos', sa.Column('numeroguia', sa.String(length=300), nullable=True))
    op.alter_column('shop', 'sueldo_mensual',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shop', 'sueldo_mensual',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.drop_column('pedidos', 'numeroguia')
    # ### end Alembic commands ###
