"""crear rol en tabla usuarios

Revision ID: 797089148fe9
Revises: 4b1a0d6a4af5
Create Date: 2026-08-13 15:26:10.457784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '797089148fe9'
down_revision: Union[str, Sequence[str], None] = '4b1a0d6a4af5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('rol', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'rol')
    # ### end Alembic commands ###
