"""tabla de combos

Revision ID: 7c01341e0175
Revises: 8343864782e4
Create Date: 2026-08-26 17:25:05.351467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c01341e0175'
down_revision: Union[str, Sequence[str], None] = '8343864782e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('combos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_tienda', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('precio', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_tienda'], ['shop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_combos_id'), 'combos', ['id'], unique=False)
    op.create_index(op.f('ix_combos_id_tienda'), 'combos', ['id_tienda'], unique=False)
    op.create_table('combo_alimentos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('combo_id', sa.Integer(), nullable=False),
    sa.Column('alimento_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['alimento_id'], ['alimentos.id'], ),
    sa.ForeignKeyConstraint(['combo_id'], ['combos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('combo_id', 'alimento_id', name='uq_combo_alimento')
    )
    op.create_index(op.f('ix_combo_alimentos_alimento_id'), 'combo_alimentos', ['alimento_id'], unique=False)
    op.create_index(op.f('ix_combo_alimentos_combo_id'), 'combo_alimentos', ['combo_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_combo_alimentos_combo_id'), table_name='combo_alimentos')
    op.drop_index(op.f('ix_combo_alimentos_alimento_id'), table_name='combo_alimentos')
    op.drop_table('combo_alimentos')
    op.drop_index(op.f('ix_combos_id_tienda'), table_name='combos')
    op.drop_index(op.f('ix_combos_id'), table_name='combos')
    op.drop_table('combos')
    # ### end Alembic commands ###
