"""atributoos nuevos para pedidos

Revision ID: 8abf1026d09a
Revises: 0f162b8a4bda
Create Date: 2026-08-28 18:35:55.863923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8abf1026d09a'
down_revision: Union[str, Sequence[str], None] = '0f162b8a4bda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedidos', sa.Column('nombresyapellidos', sa.String(length=100), nullable=True))
    op.add_column('pedidos', sa.Column('telefonocliente', sa.String(length=20), nullable=True))
    op.add_column('pedidos', sa.Column('ciudadcliente', sa.String(length=100), nullable=True))
    op.add_column('pedidos', sa.Column('direccioncliente', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pedidos', 'direccioncliente')
    op.drop_column('pedidos', 'ciudadcliente')
    op.drop_column('pedidos', 'telefonocliente')
    op.drop_column('pedidos', 'nombresyapellidos')
    # ### end Alembic commands ###
