"""crear tabla productos

Revision ID: 8dc8d70953ad
Revises: eba478b6decd
Create Date: 2026-08-14 23:17:44.667471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dc8d70953ad'
down_revision: Union[str, Sequence[str], None] = 'eba478b6decd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_tienda', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('precio', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.Column('imagen1', sa.String(length=300), nullable=True),
    sa.Column('imagen2', sa.String(length=300), nullable=True),
    sa.Column('creado_fecha', sa.DateTime(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['id_tienda'], ['shop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_productos_id'), 'productos', ['id'], unique=False)
    op.create_index(op.f('ix_productos_id_tienda'), 'productos', ['id_tienda'], unique=False)
    op.create_table('productos_simples',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('producto_id')
    )
    op.create_index(op.f('ix_productos_simples_id'), 'productos_simples', ['id'], unique=False)
    op.create_table('productos_variantes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('talla', sa.String(length=30), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_productos_variantes_id'), 'productos_variantes', ['id'], unique=False)
    op.create_index(op.f('ix_productos_variantes_producto_id'), 'productos_variantes', ['producto_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_productos_variantes_producto_id'), table_name='productos_variantes')
    op.drop_index(op.f('ix_productos_variantes_id'), table_name='productos_variantes')
    op.drop_table('productos_variantes')
    op.drop_index(op.f('ix_productos_simples_id'), table_name='productos_simples')
    op.drop_table('productos_simples')
    op.drop_index(op.f('ix_productos_id_tienda'), table_name='productos')
    op.drop_index(op.f('ix_productos_id'), table_name='productos')
    op.drop_table('productos')
    # ### end Alembic commands ###
