"""corregi atributo plantillas en shop

Revision ID: 907f59770b28
Revises: 2a9d8cc57a77
Create Date: 2026-08-22 13:13:12.704920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '907f59770b28'
down_revision: Union[str, Sequence[str], None] = '2a9d8cc57a77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop', sa.Column('plantilla', sa.Integer(), nullable=False))
    op.drop_column('shop', 'pantilla')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop', sa.Column('pantilla', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('shop', 'plantilla')
    # ### end Alembic commands ###
