"""tabla tu informacion y otras

Revision ID: 9f88ce4d85be
Revises: 70040e1f1de3
Create Date: 2026-09-01 21:11:51.652280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f88ce4d85be'
down_revision: Union[str, Sequence[str], None] = '70040e1f1de3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tuinformacion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('nombre_completo', sa.String(length=200), nullable=True),
    sa.Column('dedicacion', sa.String(length=150), nullable=True),
    sa.Column('dedicacion_detallada', sa.String(length=250), nullable=True),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('disponibilidad', sa.Boolean(), nullable=True),
    sa.Column('sobre_mi', sa.Text(), nullable=True),
    sa.Column('numero_telefono', sa.String(length=20), nullable=True),
    sa.Column('correo', sa.String(length=150), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['users.cedula'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tuinformacion_id'), 'tuinformacion', ['id'], unique=False)
    op.create_index(op.f('ix_tuinformacion_id_usuario'), 'tuinformacion', ['id_usuario'], unique=False)
    op.create_table('comofunciona',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_tu_informacion', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_tu_informacion'], ['tuinformacion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comofunciona_id'), 'comofunciona', ['id'], unique=False)
    op.create_index(op.f('ix_comofunciona_id_tu_informacion'), 'comofunciona', ['id_tu_informacion'], unique=False)
    op.create_table('informacionservicio',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_tu_informacion', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_tu_informacion'], ['tuinformacion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_informacionservicio_id'), 'informacionservicio', ['id'], unique=False)
    op.create_index(op.f('ix_informacionservicio_id_tu_informacion'), 'informacionservicio', ['id_tu_informacion'], unique=False)
    op.create_table('miexperiencia',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_tu_informacion', sa.Integer(), nullable=False),
    sa.Column('anos_experiencia', sa.Integer(), nullable=True),
    sa.Column('clientes_atendidos', sa.Integer(), nullable=True),
    sa.Column('calificacion_promedio', sa.Float(), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_tu_informacion'], ['tuinformacion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_miexperiencia_id'), 'miexperiencia', ['id'], unique=False)
    op.create_index(op.f('ix_miexperiencia_id_tu_informacion'), 'miexperiencia', ['id_tu_informacion'], unique=False)
    op.create_table('misespecialidades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_tu_informacion', sa.Integer(), nullable=False),
    sa.Column('icon', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_tu_informacion'], ['tuinformacion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_misespecialidades_id'), 'misespecialidades', ['id'], unique=False)
    op.create_index(op.f('ix_misespecialidades_id_tu_informacion'), 'misespecialidades', ['id_tu_informacion'], unique=False)
    op.create_table('porquetrabajarconmigo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_tu_informacion', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_tu_informacion'], ['tuinformacion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_porquetrabajarconmigo_id'), 'porquetrabajarconmigo', ['id'], unique=False)
    op.create_index(op.f('ix_porquetrabajarconmigo_id_tu_informacion'), 'porquetrabajarconmigo', ['id_tu_informacion'], unique=False)
    op.create_table('quehago',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_tu_informacion', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('icon', sa.String(length=100), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_tu_informacion'], ['tuinformacion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quehago_id'), 'quehago', ['id'], unique=False)
    op.create_index(op.f('ix_quehago_id_tu_informacion'), 'quehago', ['id_tu_informacion'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quehago_id_tu_informacion'), table_name='quehago')
    op.drop_index(op.f('ix_quehago_id'), table_name='quehago')
    op.drop_table('quehago')
    op.drop_index(op.f('ix_porquetrabajarconmigo_id_tu_informacion'), table_name='porquetrabajarconmigo')
    op.drop_index(op.f('ix_porquetrabajarconmigo_id'), table_name='porquetrabajarconmigo')
    op.drop_table('porquetrabajarconmigo')
    op.drop_index(op.f('ix_misespecialidades_id_tu_informacion'), table_name='misespecialidades')
    op.drop_index(op.f('ix_misespecialidades_id'), table_name='misespecialidades')
    op.drop_table('misespecialidades')
    op.drop_index(op.f('ix_miexperiencia_id_tu_informacion'), table_name='miexperiencia')
    op.drop_index(op.f('ix_miexperiencia_id'), table_name='miexperiencia')
    op.drop_table('miexperiencia')
    op.drop_index(op.f('ix_informacionservicio_id_tu_informacion'), table_name='informacionservicio')
    op.drop_index(op.f('ix_informacionservicio_id'), table_name='informacionservicio')
    op.drop_table('informacionservicio')
    op.drop_index(op.f('ix_comofunciona_id_tu_informacion'), table_name='comofunciona')
    op.drop_index(op.f('ix_comofunciona_id'), table_name='comofunciona')
    op.drop_table('comofunciona')
    op.drop_index(op.f('ix_tuinformacion_id_usuario'), table_name='tuinformacion')
    op.drop_index(op.f('ix_tuinformacion_id'), table_name='tuinformacion')
    op.drop_table('tuinformacion')
    # ### end Alembic commands ###
