"""quitar atributos de imagenes

Revision ID: b5c5493b2101
Revises: d70accc7fb5b
Create Date: 2026-08-20 19:19:57.120710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b5c5493b2101'
down_revision: Union[str, Sequence[str], None] = 'd70accc7fb5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('estilos', 'imagen_fondo')
    op.drop_column('productos', 'imagen1')
    op.drop_column('productos', 'imagen2')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productos', sa.Column('imagen2', mysql.VARCHAR(length=300), nullable=True))
    op.add_column('productos', sa.Column('imagen1', mysql.VARCHAR(length=300), nullable=True))
    op.add_column('estilos', sa.Column('imagen_fondo', mysql.VARCHAR(length=300), nullable=True))
    # ### end Alembic commands ###
