"""imagenes ahora en las variantes, y marcas y referencias

Revision ID: bac41985133a
Revises: b5c5493b2101
Create Date: 2026-08-20 19:26:31.534186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bac41985133a'
down_revision: Union[str, Sequence[str], None] = 'b5c5493b2101'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productos_simples', sa.Column('marca', sa.String(length=100), nullable=True))
    op.add_column('productos_simples', sa.Column('referencia', sa.String(length=100), nullable=True))
    op.add_column('productos_simples', sa.Column('imagen', sa.String(length=250), nullable=True))
    op.add_column('productos_variantes', sa.Column('marca', sa.String(length=100), nullable=True))
    op.add_column('productos_variantes', sa.Column('referencia', sa.String(length=100), nullable=True))
    op.add_column('productos_variantes', sa.Column('imagen', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productos_variantes', 'imagen')
    op.drop_column('productos_variantes', 'referencia')
    op.drop_column('productos_variantes', 'marca')
    op.drop_column('productos_simples', 'imagen')
    op.drop_column('productos_simples', 'referencia')
    op.drop_column('productos_simples', 'marca')
    # ### end Alembic commands ###
