"""tabla suscripciones

Revision ID: bff0be47db82
Revises: fee1c344e0da
Create Date: 2026-09-04 12:52:44.660827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bff0be47db82'
down_revision: Union[str, Sequence[str], None] = 'fee1c344e0da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suscripciones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cedula_usuario', sa.Integer(), nullable=False),
    sa.Column('cantidad_pagar', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('fecha_pago', sa.DateTime(), nullable=True),
    sa.Column('referencia_pago', sa.String(length=100), nullable=True),
    sa.Column('metodo_pago', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['cedula_usuario'], ['users.cedula'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suscripciones_cedula_usuario'), 'suscripciones', ['cedula_usuario'], unique=False)
    op.create_index(op.f('ix_suscripciones_id'), 'suscripciones', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_suscripciones_id'), table_name='suscripciones')
    op.drop_index(op.f('ix_suscripciones_cedula_usuario'), table_name='suscripciones')
    op.drop_table('suscripciones')
    # ### end Alembic commands ###
