"""cambio atributo de tu info

Revision ID: cfdc6549aa5b
Revises: 9f88ce4d85be
Create Date: 2026-09-01 21:17:50.688230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cfdc6549aa5b'
down_revision: Union[str, Sequence[str], None] = '9f88ce4d85be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tuinformacion', 'id_usuario',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tuinformacion', 'id_usuario',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
