"""agregar correo en pedidos

Revision ID: d70accc7fb5b
Revises: 2b9a06a7d8ad
Create Date: 2026-08-17 18:09:58.612391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd70accc7fb5b'
down_revision: Union[str, Sequence[str], None] = '2b9a06a7d8ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedidos', sa.Column('correocliente', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pedidos', 'correocliente')
    # ### end Alembic commands ###
