"""crear tabla shop nuevos datos

Revision ID: eba478b6decd
Revises: 705b68c2b222
Create Date: 2026-08-13 16:49:51.722218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eba478b6decd'
down_revision: Union[str, Sequence[str], None] = '705b68c2b222'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=False),
    sa.Column('sueldo_mensual', sa.String(length=50), nullable=False),
    sa.Column('actividad', sa.String(length=150), nullable=False),
    sa.Column('pasarela_pagos', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('dominio', sa.String(length=150), nullable=False),
    sa.Column('estado', sa.Boolean(), nullable=False),
    sa.Column('logo', sa.String(length=300), nullable=True),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.cedula'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_index(op.f('ix_shop_dominio'), 'shop', ['dominio'], unique=True)
    op.create_index(op.f('ix_shop_id'), 'shop', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shop_id'), table_name='shop')
    op.drop_index(op.f('ix_shop_dominio'), table_name='shop')
    op.drop_table('shop')
    # ### end Alembic commands ###
